# Generated by Django 4.0 on 2022-01-02 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название датчика')),
                ('description', models.CharField(blank=True, max_length=100, verbose_name='Описание (необязательно)')),
            ],
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.IntegerField(verbose_name='Температура при измерении')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Дата измерений')),
                ('image', models.ImageField(blank=True, default=None, upload_to='measurements/%Y/%m/%d')),
                ('sensor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='measurement.sensor', verbose_name='ID датчика')),
            ],
        ),
    ]
